### ISSUE TITLE
[BR] Unicode characters not rendering correctly.

### ISSUE THREAD

**Issue by marvin-martian** [bus-stop/terminus#210]
- [x] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
- [ ] I have tried uninstalling/reinstalling the terminal.
- [ ] I have not tried uninstalling/reinstalling the terminal.
### Description
Some extended unicode characters do not render correctly in the terminal.

### Steps to reproduce
Copy and paste this in your terminus terminal with brackets: 
```
> [⚑] 
```

**Expected behavior:**
It should be looking exactly the same: 
```
> [⚑] 
```

**Actual behavior:**
It loses the last character: 
```
> [⚑
```

**Reproduces how often:**
All the time.

### Versions

```
> atom --version
Atom    : 1.55.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0
```

```
> apm --version
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.55.0
python 2.7.18
git 2.25.1
```
OS name and version: Ubuntu 20.04.2 LTS
Terminal version: 4.1.3

### Additional context
None.

**Comment by the-j0k3r** [comment]
[⚑]

**Comment by the-j0k3r** [comment]
Hello, thx for report, could you please share your terminus config with us.

You may need to escape the close bracket, like `[⚑\\]' its works fine like that though it seems some odd spacing is introduced.

We just read and paste the clipboard contents (see below),

https://github.com/bus-stop/terminus/blob/3990b9c1795a5b8d915eee702dd53f991d1ed3c5/lib/view.js#L548-L550

Pasting it on real terminal works fine so some extra logic will be needed.

**Comment by marvin-martian** [comment]
It is not the font because I use the same "Monospace" font in the Ubuntu Terminal and in the normal terminal it shows fine. In the edit area within Atom it also shows up fine. It is not just when you paste it in. If I run a small js script `console.log('[⚑]');` that sends to stdout in Terminus it is also mis-renders it.

So it is probably not the clipboard. 

It is not the only unicode character that does it, it seems to happen on every character from the [Unicode Miscellanous Symbols](https://en.wikipedia.org/wiki/Miscellaneous_Symbols) Maybe there are other Unicode Blocks that this also effects, but I haven't checked.

Maybe it is upstream in  ('node-pty-prebuilt-multiarch') ?? I am not sure. I haven't dug/played with the Terminus  code, and I don't know much about 'node-pty'. I just quickly glanced at terminus/lib/view.js now.

This is what is in my config.cson for terminus (everything else would be default settings):
````
  terminus:
    ansiColors:
      normal:
        blue: "#268bd2"
        cyan: "#2aa198"
        green: "#859900"
        magenta: "#d33682"
        red: "#dc322f"
        yellow: "#b58900"
      zBright:
        brightBlue: "#268bd2"
        brightCyan: "#2aa198"
        brightGreen: "#859900"
        brightMagenta: "#d33682"
        brightRed: "#dc322f"
        brightYellow: "#b58900"
    iconColors:
      blue: "#268bd2"
      cyan: "#2aa198"
      green: "#859900"
      magenta: "#d33682"
      orange: "#cb4b16"
      red: "#dc322f"
      yellow: "#b58900"
    style:
      fontFamily: "Monospace"
      theme: "atom-dark"
````
