### ISSUE TITLE
[FR] Add options to the cursor

### ISSUE THREAD

**Issue by TJProgrammer** [bus-stop/terminus#59]
### Describe the feature you'd like

Add options in settings to change the cursor behavior.
And for blinking:
![Captura de ecrã de 2020-02-12 19-08-24](https://user-images.githubusercontent.com/7900361/74368323-53ed9380-4dcb-11ea-8e79-0678c5a47eab.png)

For example: block, pipe or underscore
![Captura de ecrã de 2020-02-12 19-08-33](https://user-images.githubusercontent.com/7900361/74368351-5ea82880-4dcb-11ea-9114-2f621ca921a5.png)

**Comment by the-j0k3r** [comment]
Were working on another project here on bus-stop the [x-terminal](https://github.com/bus-stop/x-terminal)

With this other project which is based in xterm, you have options to do this see https://github.com/bus-stop/x-terminal/issues/14#issue-573303104 and [/iterminaloptions/#cursor](https://xtermjs.org/docs/api/terminal/interfaces/iterminaloptions/#cursorblink)for more specific info on this from x-terminal.

This project is still term.js based so these things are unlikely to happen with xterm.js, except for Atom stylesheet hacks. Ill post some later.

**Comment by TJProgrammer** [comment]
Ok, thank you. I'll wait for terminus CSS.

**Comment by the-j0k3r** [comment]
# Underline 
```css
@import "ui-variables";

.terminal-view {
    .cursor-blink {
      .terminal-cursor {
        -webkit-animation: blink 1s step-start 0s infinite;
        -webkit-animation-delay: 1s;
        border-bottom: 2px solid @accent-color;
        background: transparent;
        @-webkit-keyframes blink {
          50%  { 
            background: transparent;
            border-bottom: 2px solid transparent;
          }
        }
      }
    }
  }
```
# I-Beam

```css
.terminal-view {
    .cursor-blink {
      .terminal-cursor {
        -webkit-animation: blink 1s step-start 0s infinite;
        -webkit-animation-delay: 1s;
        border-left: 2px solid @accent-color;
        background: transparent;
        @-webkit-keyframes blink {
          50%  { 
            background: transparent;
            border-left: 2px solid transparent;
          }
        }
      }
    }
  }
```
